// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bol-catalog/bol_catalog.proto

package bol_catalog_v1beta1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateProductResponse_Status int32

const (
	UpdateProductResponse_UNEXPECTED_ERROR UpdateProductResponse_Status = 0
	UpdateProductResponse_SUCCESS          UpdateProductResponse_Status = 1
	// The product you provided as the "expectedProduct" does not match the product in the database, this usually means
	UpdateProductResponse_NOT_EQUAL_EXPECTED UpdateProductResponse_Status = 2
	// The product by the id does not exist
	UpdateProductResponse_NOT_EXIST UpdateProductResponse_Status = 3
	// Eg. when the id fields of the newProduct and expectedProduct do not match
	UpdateProductResponse_SYNTAX_ERROR UpdateProductResponse_Status = 4
)

var UpdateProductResponse_Status_name = map[int32]string{
	0: "UNEXPECTED_ERROR",
	1: "SUCCESS",
	2: "NOT_EQUAL_EXPECTED",
	3: "NOT_EXIST",
	4: "SYNTAX_ERROR",
}

var UpdateProductResponse_Status_value = map[string]int32{
	"UNEXPECTED_ERROR":   0,
	"SUCCESS":            1,
	"NOT_EQUAL_EXPECTED": 2,
	"NOT_EXIST":          3,
	"SYNTAX_ERROR":       4,
}

func (x UpdateProductResponse_Status) String() string {
	return proto.EnumName(UpdateProductResponse_Status_name, int32(x))
}

func (UpdateProductResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_705d7c1b5219fa7d, []int{7, 0}
}

type DeleteProductResponse_Status int32

const (
	DeleteProductResponse_UNEXPECTED_ERROR DeleteProductResponse_Status = 0
	// Delete was successful
	DeleteProductResponse_SUCCESS DeleteProductResponse_Status = 1
	// Product was not found, usually when the deletion already happened.
	DeleteProductResponse_NOT_FOUND DeleteProductResponse_Status = 2
)

var DeleteProductResponse_Status_name = map[int32]string{
	0: "UNEXPECTED_ERROR",
	1: "SUCCESS",
	2: "NOT_FOUND",
}

var DeleteProductResponse_Status_value = map[string]int32{
	"UNEXPECTED_ERROR": 0,
	"SUCCESS":          1,
	"NOT_FOUND":        2,
}

func (x DeleteProductResponse_Status) String() string {
	return proto.EnumName(DeleteProductResponse_Status_name, int32(x))
}

func (DeleteProductResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_705d7c1b5219fa7d, []int{9, 0}
}

type GetProductResponse_Status int32

const (
	GetProductResponse_UNEXPECTED_ERROR GetProductResponse_Status = 0
	GetProductResponse_SUCCESS          GetProductResponse_Status = 1
	GetProductResponse_NOT_FOUND        GetProductResponse_Status = 2
)

var GetProductResponse_Status_name = map[int32]string{
	0: "UNEXPECTED_ERROR",
	1: "SUCCESS",
	2: "NOT_FOUND",
}

var GetProductResponse_Status_value = map[string]int32{
	"UNEXPECTED_ERROR": 0,
	"SUCCESS":          1,
	"NOT_FOUND":        2,
}

func (x GetProductResponse_Status) String() string {
	return proto.EnumName(GetProductResponse_Status_name, int32(x))
}

func (GetProductResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_705d7c1b5219fa7d, []int{11, 0}
}

type AddProductResponse_Status int32

const (
	// Something unexpected happened
	AddProductResponse_UNEXPECTED_ERROR AddProductResponse_Status = 0
	AddProductResponse_SUCCESS          AddProductResponse_Status = 1
	// When a product with one of the identifying fields already exists
	AddProductResponse_ALREADY_EXISTS AddProductResponse_Status = 2
	// When the id is set for example
	AddProductResponse_BAD_CONTENTS AddProductResponse_Status = 3
)

var AddProductResponse_Status_name = map[int32]string{
	0: "UNEXPECTED_ERROR",
	1: "SUCCESS",
	2: "ALREADY_EXISTS",
	3: "BAD_CONTENTS",
}

var AddProductResponse_Status_value = map[string]int32{
	"UNEXPECTED_ERROR": 0,
	"SUCCESS":          1,
	"ALREADY_EXISTS":   2,
	"BAD_CONTENTS":     3,
}

func (x AddProductResponse_Status) String() string {
	return proto.EnumName(AddProductResponse_Status_name, int32(x))
}

func (AddProductResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_705d7c1b5219fa7d, []int{13, 0}
}

// A product within the bol.com catalog
type Product struct {
	// a unique identifier that is unrelated to bol.com
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The product name, also called title
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The product subtitle
	Subtitle string `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	// A short description of the product
	ShortDescription string `protobuf:"bytes,4,opt,name=shortDescription,proto3" json:"shortDescription,omitempty"`
	// Contains the amount of various types of sellers
	OffersMeta *OffersMeta `protobuf:"bytes,5,opt,name=offersMeta,proto3" json:"offersMeta,omitempty"`
	// Average product rating, scale 00-50, representing 0 to 5 stars
	Rating uint32 `protobuf:"varint,6,opt,name=rating,proto3" json:"rating,omitempty"`
	// The EAN code of the product
	Ean string `protobuf:"bytes,7,opt,name=ean,proto3" json:"ean,omitempty"`
	// The GPC classification for the product
	Gpc string `protobuf:"bytes,8,opt,name=gpc,proto3" json:"gpc,omitempty"`
	// Time the product record was initially created, do not update/set this manually.
	CreatedTimestamp uint64 `protobuf:"varint,9,opt,name=createdTimestamp,proto3" json:"createdTimestamp,omitempty"`
	// Last time the data for this product was updated, unix timestamp, do not update/set this manually
	UpdatedTimestamp     uint64   `protobuf:"varint,10,opt,name=updatedTimestamp,proto3" json:"updatedTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_705d7c1b5219fa7d, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetSubtitle() string {
	if m != nil {
		return m.Subtitle
	}
	return ""
}

func (m *Product) GetShortDescription() string {
	if m != nil {
		return m.ShortDescription
	}
	return ""
}

func (m *Product) GetOffersMeta() *OffersMeta {
	if m != nil {
		return m.OffersMeta
	}
	return nil
}

func (m *Product) GetRating() uint32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Product) GetEan() string {
	if m != nil {
		return m.Ean
	}
	return ""
}

func (m *Product) GetGpc() string {
	if m != nil {
		return m.Gpc
	}
	return ""
}

func (m *Product) GetCreatedTimestamp() uint64 {
	if m != nil {
		return m.CreatedTimestamp
	}
	return 0
}

func (m *Product) GetUpdatedTimestamp() uint64 {
	if m != nil {
		return m.UpdatedTimestamp
	}
	return 0
}

// Metadata of the sellers of a product (just contains the amount of sellers of each type)
type OffersMeta struct {
	// The number of bol.com offers for the product
	Bolcom uint32 `protobuf:"varint,1,opt,name=bolcom,proto3" json:"bolcom,omitempty"`
	// The number of nonprofessional sellers for the product
	NonProfessional uint32 `protobuf:"varint,2,opt,name=nonProfessional,proto3" json:"nonProfessional,omitempty"`
	// The number of professional seller offers for the product
	Professional         uint32   `protobuf:"varint,3,opt,name=professional,proto3" json:"professional,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OffersMeta) Reset()         { *m = OffersMeta{} }
func (m *OffersMeta) String() string { return proto.CompactTextString(m) }
func (*OffersMeta) ProtoMessage()    {}
func (*OffersMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_705d7c1b5219fa7d, []int{1}
}

func (m *OffersMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OffersMeta.Unmarshal(m, b)
}
func (m *OffersMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OffersMeta.Marshal(b, m, deterministic)
}
func (m *OffersMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OffersMeta.Merge(m, src)
}
func (m *OffersMeta) XXX_Size() int {
	return xxx_messageInfo_OffersMeta.Size(m)
}
func (m *OffersMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_OffersMeta.DiscardUnknown(m)
}

var xxx_messageInfo_OffersMeta proto.InternalMessageInfo

func (m *OffersMeta) GetBolcom() uint32 {
	if m != nil {
		return m.Bolcom
	}
	return 0
}

func (m *OffersMeta) GetNonProfessional() uint32 {
	if m != nil {
		return m.NonProfessional
	}
	return 0
}

func (m *OffersMeta) GetProfessional() uint32 {
	if m != nil {
		return m.Professional
	}
	return 0
}

type Offer struct {
	// Uniquely generated id for the offer, note this is not the bol.com offerId
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The offer ID by Bol.
	OfferId string `protobuf:"bytes,2,opt,name=offerId,proto3" json:"offerId,omitempty"`
	// The unique id of the product this offer relates to (see Product)
	ProductId string `protobuf:"bytes,3,opt,name=productId,proto3" json:"productId,omitempty"`
	// The bol.com price, format 19.95
	Price string `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	// The list price, format 19.95
	ListPrice string `protobuf:"bytes,5,opt,name=listPrice,proto3" json:"listPrice,omitempty"`
	//The seller of the product
	Seller *Seller `protobuf:"bytes,6,opt,name=seller,proto3" json:"seller,omitempty"`
	// Whether this offer is the best offer
	BestOffer            bool     `protobuf:"varint,7,opt,name=bestOffer,proto3" json:"bestOffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Offer) Reset()         { *m = Offer{} }
func (m *Offer) String() string { return proto.CompactTextString(m) }
func (*Offer) ProtoMessage()    {}
func (*Offer) Descriptor() ([]byte, []int) {
	return fileDescriptor_705d7c1b5219fa7d, []int{2}
}

func (m *Offer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Offer.Unmarshal(m, b)
}
func (m *Offer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Offer.Marshal(b, m, deterministic)
}
func (m *Offer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Offer.Merge(m, src)
}
func (m *Offer) XXX_Size() int {
	return xxx_messageInfo_Offer.Size(m)
}
func (m *Offer) XXX_DiscardUnknown() {
	xxx_messageInfo_Offer.DiscardUnknown(m)
}

var xxx_messageInfo_Offer proto.InternalMessageInfo

func (m *Offer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Offer) GetOfferId() string {
	if m != nil {
		return m.OfferId
	}
	return ""
}

func (m *Offer) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *Offer) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Offer) GetListPrice() string {
	if m != nil {
		return m.ListPrice
	}
	return ""
}

func (m *Offer) GetSeller() *Seller {
	if m != nil {
		return m.Seller
	}
	return nil
}

func (m *Offer) GetBestOffer() bool {
	if m != nil {
		return m.BestOffer
	}
	return false
}

type Seller struct {
	// Uniquely generated id, not the bol id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Bol.com assigned id
	SellerId string `protobuf:"bytes,2,opt,name=sellerId,proto3" json:"sellerId,omitempty"`
	// Display name for the seller
	DisplayName          string   `protobuf:"bytes,3,opt,name=displayName,proto3" json:"displayName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Seller) Reset()         { *m = Seller{} }
func (m *Seller) String() string { return proto.CompactTextString(m) }
func (*Seller) ProtoMessage()    {}
func (*Seller) Descriptor() ([]byte, []int) {
	return fileDescriptor_705d7c1b5219fa7d, []int{3}
}

func (m *Seller) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Seller.Unmarshal(m, b)
}
func (m *Seller) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Seller.Marshal(b, m, deterministic)
}
func (m *Seller) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Seller.Merge(m, src)
}
func (m *Seller) XXX_Size() int {
	return xxx_messageInfo_Seller.Size(m)
}
func (m *Seller) XXX_DiscardUnknown() {
	xxx_messageInfo_Seller.DiscardUnknown(m)
}

var xxx_messageInfo_Seller proto.InternalMessageInfo

func (m *Seller) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Seller) GetSellerId() string {
	if m != nil {
		return m.SellerId
	}
	return ""
}

func (m *Seller) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

// You should only assume there are no new products when the server returns 0 products.
// In case your ascending you can also add another check when the latest timestamp comes close to the present.
// This way you don't keep following up on newly added products.
type ListProductRequest struct {
	Pager                *Pager   `protobuf:"bytes,1,opt,name=pager,proto3" json:"pager,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProductRequest) Reset()         { *m = ListProductRequest{} }
func (m *ListProductRequest) String() string { return proto.CompactTextString(m) }
func (*ListProductRequest) ProtoMessage()    {}
func (*ListProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_705d7c1b5219fa7d, []int{4}
}

func (m *ListProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductRequest.Unmarshal(m, b)
}
func (m *ListProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductRequest.Marshal(b, m, deterministic)
}
func (m *ListProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductRequest.Merge(m, src)
}
func (m *ListProductRequest) XXX_Size() int {
	return xxx_messageInfo_ListProductRequest.Size(m)
}
func (m *ListProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductRequest proto.InternalMessageInfo

func (m *ListProductRequest) GetPager() *Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

// A pager helps with paging through lists of resources.
// We recommend listing in descending from the current time until there are no more resources.
type Pager struct {
	// The maximum amount of items to return. The server may also enforce a maximum server-side (Default is around 100).
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Start the list from this timestamp, set ascending to list items with a createdTimestamp greater then fromTimestamp,
	// descending from less then.
	FromTimestamp uint64 `protobuf:"varint,2,opt,name=fromTimestamp,proto3" json:"fromTimestamp,omitempty"`
	// if set to true it will return items created after fromTimestamp, otherwise before fromTimestamp.
	Ascending            bool     `protobuf:"varint,3,opt,name=ascending,proto3" json:"ascending,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pager) Reset()         { *m = Pager{} }
func (m *Pager) String() string { return proto.CompactTextString(m) }
func (*Pager) ProtoMessage()    {}
func (*Pager) Descriptor() ([]byte, []int) {
	return fileDescriptor_705d7c1b5219fa7d, []int{5}
}

func (m *Pager) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pager.Unmarshal(m, b)
}
func (m *Pager) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pager.Marshal(b, m, deterministic)
}
func (m *Pager) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pager.Merge(m, src)
}
func (m *Pager) XXX_Size() int {
	return xxx_messageInfo_Pager.Size(m)
}
func (m *Pager) XXX_DiscardUnknown() {
	xxx_messageInfo_Pager.DiscardUnknown(m)
}

var xxx_messageInfo_Pager proto.InternalMessageInfo

func (m *Pager) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Pager) GetFromTimestamp() uint64 {
	if m != nil {
		return m.FromTimestamp
	}
	return 0
}

func (m *Pager) GetAscending() bool {
	if m != nil {
		return m.Ascending
	}
	return false
}

type UpdateProductRequest struct {
	// The product you are expecting (not setting this will force override the product).
	// Fields that are not set will not be changed. Deleting fields is currently not supported (other then setting them to 0 or "").
	ExpectedProduct *Product `protobuf:"bytes,1,opt,name=expectedProduct,proto3" json:"expectedProduct,omitempty"`
	// The new version of the product (ean and id should be the same as the expected_product or SYNTAX_ERROR will be returned)
	NewProduct           *Product `protobuf:"bytes,2,opt,name=newProduct,proto3" json:"newProduct,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductRequest) Reset()         { *m = UpdateProductRequest{} }
func (m *UpdateProductRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProductRequest) ProtoMessage()    {}
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_705d7c1b5219fa7d, []int{6}
}

func (m *UpdateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductRequest.Unmarshal(m, b)
}
func (m *UpdateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductRequest.Merge(m, src)
}
func (m *UpdateProductRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProductRequest.Size(m)
}
func (m *UpdateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductRequest proto.InternalMessageInfo

func (m *UpdateProductRequest) GetExpectedProduct() *Product {
	if m != nil {
		return m.ExpectedProduct
	}
	return nil
}

func (m *UpdateProductRequest) GetNewProduct() *Product {
	if m != nil {
		return m.NewProduct
	}
	return nil
}

type UpdateProductResponse struct {
	// The current product after the update (or when the update was not successful)
	Current              *Product                     `protobuf:"bytes,1,opt,name=current,proto3" json:"current,omitempty"`
	Status               UpdateProductResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=bol_catalog_v1beta1.UpdateProductResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *UpdateProductResponse) Reset()         { *m = UpdateProductResponse{} }
func (m *UpdateProductResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProductResponse) ProtoMessage()    {}
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_705d7c1b5219fa7d, []int{7}
}

func (m *UpdateProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductResponse.Unmarshal(m, b)
}
func (m *UpdateProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductResponse.Marshal(b, m, deterministic)
}
func (m *UpdateProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductResponse.Merge(m, src)
}
func (m *UpdateProductResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProductResponse.Size(m)
}
func (m *UpdateProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductResponse proto.InternalMessageInfo

func (m *UpdateProductResponse) GetCurrent() *Product {
	if m != nil {
		return m.Current
	}
	return nil
}

func (m *UpdateProductResponse) GetStatus() UpdateProductResponse_Status {
	if m != nil {
		return m.Status
	}
	return UpdateProductResponse_UNEXPECTED_ERROR
}

type DeleteProductRequest struct {
	// The product to delete: One of the identifying fields (ean, id) should be set.
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductRequest) Reset()         { *m = DeleteProductRequest{} }
func (m *DeleteProductRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProductRequest) ProtoMessage()    {}
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_705d7c1b5219fa7d, []int{8}
}

func (m *DeleteProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductRequest.Unmarshal(m, b)
}
func (m *DeleteProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductRequest.Marshal(b, m, deterministic)
}
func (m *DeleteProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductRequest.Merge(m, src)
}
func (m *DeleteProductRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProductRequest.Size(m)
}
func (m *DeleteProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductRequest proto.InternalMessageInfo

func (m *DeleteProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type DeleteProductResponse struct {
	// Whether or not the deletion was successful
	Status               DeleteProductResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=bol_catalog_v1beta1.DeleteProductResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *DeleteProductResponse) Reset()         { *m = DeleteProductResponse{} }
func (m *DeleteProductResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteProductResponse) ProtoMessage()    {}
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_705d7c1b5219fa7d, []int{9}
}

func (m *DeleteProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductResponse.Unmarshal(m, b)
}
func (m *DeleteProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductResponse.Marshal(b, m, deterministic)
}
func (m *DeleteProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductResponse.Merge(m, src)
}
func (m *DeleteProductResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteProductResponse.Size(m)
}
func (m *DeleteProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductResponse proto.InternalMessageInfo

func (m *DeleteProductResponse) GetStatus() DeleteProductResponse_Status {
	if m != nil {
		return m.Status
	}
	return DeleteProductResponse_UNEXPECTED_ERROR
}

type GetProductRequest struct {
	// One of the identifying fields should be set (ean, id), all other fields can be left empty (but will also cause filtering when set).
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductRequest) Reset()         { *m = GetProductRequest{} }
func (m *GetProductRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductRequest) ProtoMessage()    {}
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_705d7c1b5219fa7d, []int{10}
}

func (m *GetProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductRequest.Unmarshal(m, b)
}
func (m *GetProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductRequest.Marshal(b, m, deterministic)
}
func (m *GetProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductRequest.Merge(m, src)
}
func (m *GetProductRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductRequest.Size(m)
}
func (m *GetProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductRequest proto.InternalMessageInfo

func (m *GetProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type GetProductResponse struct {
	// The actual stored product
	Product              *Product                  `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Status               GetProductResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=bol_catalog_v1beta1.GetProductResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetProductResponse) Reset()         { *m = GetProductResponse{} }
func (m *GetProductResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductResponse) ProtoMessage()    {}
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_705d7c1b5219fa7d, []int{11}
}

func (m *GetProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductResponse.Unmarshal(m, b)
}
func (m *GetProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductResponse.Marshal(b, m, deterministic)
}
func (m *GetProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductResponse.Merge(m, src)
}
func (m *GetProductResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductResponse.Size(m)
}
func (m *GetProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductResponse proto.InternalMessageInfo

func (m *GetProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *GetProductResponse) GetStatus() GetProductResponse_Status {
	if m != nil {
		return m.Status
	}
	return GetProductResponse_UNEXPECTED_ERROR
}

type AddProductRequest struct {
	// The product to add, id may not be set (but ean should)
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProductRequest) Reset()         { *m = AddProductRequest{} }
func (m *AddProductRequest) String() string { return proto.CompactTextString(m) }
func (*AddProductRequest) ProtoMessage()    {}
func (*AddProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_705d7c1b5219fa7d, []int{12}
}

func (m *AddProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductRequest.Unmarshal(m, b)
}
func (m *AddProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductRequest.Marshal(b, m, deterministic)
}
func (m *AddProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductRequest.Merge(m, src)
}
func (m *AddProductRequest) XXX_Size() int {
	return xxx_messageInfo_AddProductRequest.Size(m)
}
func (m *AddProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductRequest proto.InternalMessageInfo

func (m *AddProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type AddProductResponse struct {
	// The actual product in the database (with the unique id). This is set on SUCCESS and ALREADY_EXISTS.
	Product *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	// The status code of the request
	Status AddProductResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=bol_catalog_v1beta1.AddProductResponse_Status" json:"status,omitempty"`
	// Some extra information regarding the status code, optional.
	StatusMessage        string   `protobuf:"bytes,3,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProductResponse) Reset()         { *m = AddProductResponse{} }
func (m *AddProductResponse) String() string { return proto.CompactTextString(m) }
func (*AddProductResponse) ProtoMessage()    {}
func (*AddProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_705d7c1b5219fa7d, []int{13}
}

func (m *AddProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductResponse.Unmarshal(m, b)
}
func (m *AddProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductResponse.Marshal(b, m, deterministic)
}
func (m *AddProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductResponse.Merge(m, src)
}
func (m *AddProductResponse) XXX_Size() int {
	return xxx_messageInfo_AddProductResponse.Size(m)
}
func (m *AddProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductResponse proto.InternalMessageInfo

func (m *AddProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *AddProductResponse) GetStatus() AddProductResponse_Status {
	if m != nil {
		return m.Status
	}
	return AddProductResponse_UNEXPECTED_ERROR
}

func (m *AddProductResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func init() {
	proto.RegisterEnum("bol_catalog_v1beta1.UpdateProductResponse_Status", UpdateProductResponse_Status_name, UpdateProductResponse_Status_value)
	proto.RegisterEnum("bol_catalog_v1beta1.DeleteProductResponse_Status", DeleteProductResponse_Status_name, DeleteProductResponse_Status_value)
	proto.RegisterEnum("bol_catalog_v1beta1.GetProductResponse_Status", GetProductResponse_Status_name, GetProductResponse_Status_value)
	proto.RegisterEnum("bol_catalog_v1beta1.AddProductResponse_Status", AddProductResponse_Status_name, AddProductResponse_Status_value)
	proto.RegisterType((*Product)(nil), "bol_catalog_v1beta1.Product")
	proto.RegisterType((*OffersMeta)(nil), "bol_catalog_v1beta1.OffersMeta")
	proto.RegisterType((*Offer)(nil), "bol_catalog_v1beta1.Offer")
	proto.RegisterType((*Seller)(nil), "bol_catalog_v1beta1.Seller")
	proto.RegisterType((*ListProductRequest)(nil), "bol_catalog_v1beta1.ListProductRequest")
	proto.RegisterType((*Pager)(nil), "bol_catalog_v1beta1.Pager")
	proto.RegisterType((*UpdateProductRequest)(nil), "bol_catalog_v1beta1.UpdateProductRequest")
	proto.RegisterType((*UpdateProductResponse)(nil), "bol_catalog_v1beta1.UpdateProductResponse")
	proto.RegisterType((*DeleteProductRequest)(nil), "bol_catalog_v1beta1.DeleteProductRequest")
	proto.RegisterType((*DeleteProductResponse)(nil), "bol_catalog_v1beta1.DeleteProductResponse")
	proto.RegisterType((*GetProductRequest)(nil), "bol_catalog_v1beta1.GetProductRequest")
	proto.RegisterType((*GetProductResponse)(nil), "bol_catalog_v1beta1.GetProductResponse")
	proto.RegisterType((*AddProductRequest)(nil), "bol_catalog_v1beta1.AddProductRequest")
	proto.RegisterType((*AddProductResponse)(nil), "bol_catalog_v1beta1.AddProductResponse")
}

func init() {
	proto.RegisterFile("bol-catalog/bol_catalog.proto", fileDescriptor_705d7c1b5219fa7d)
}

var fileDescriptor_705d7c1b5219fa7d = []byte{
	// 912 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xc6, 0x4e, 0x93, 0xb4, 0x27, 0x4d, 0xd7, 0x7b, 0xe8, 0xae, 0xac, 0xb2, 0x88, 0xc8, 0x42,
	0x10, 0x56, 0x22, 0x6c, 0xb3, 0xd2, 0x5e, 0x20, 0x24, 0x94, 0x4d, 0x52, 0x54, 0xd1, 0x4d, 0xb2,
	0x76, 0x02, 0xdd, 0x0b, 0x14, 0x39, 0xf6, 0x24, 0x58, 0x72, 0x3c, 0xc6, 0x33, 0x59, 0xe0, 0x8e,
	0x17, 0xe0, 0x0d, 0x10, 0x0f, 0xc4, 0x15, 0x57, 0x3c, 0x0c, 0x57, 0x68, 0xc6, 0x4e, 0xe2, 0xd8,
	0x6e, 0x49, 0x51, 0xc5, 0xdd, 0x9c, 0xcf, 0xdf, 0xf9, 0x99, 0xef, 0x9c, 0x99, 0x31, 0xbc, 0x3f,
	0xa3, 0xfe, 0xa7, 0x8e, 0xcd, 0x6d, 0x9f, 0x2e, 0x3e, 0x9b, 0x51, 0x7f, 0x9a, 0xac, 0x5b, 0x61,
	0x44, 0x39, 0xc5, 0x77, 0x53, 0xd0, 0xf4, 0xed, 0xf9, 0x8c, 0x70, 0xfb, 0xdc, 0xf8, 0x43, 0x85,
	0xea, 0x28, 0xa2, 0xee, 0xca, 0xe1, 0x78, 0x02, 0xaa, 0xe7, 0xea, 0x4a, 0x43, 0x69, 0x1e, 0x99,
	0xaa, 0xe7, 0x22, 0xc2, 0x41, 0x60, 0x2f, 0x89, 0xae, 0x4a, 0x44, 0xae, 0xf1, 0x0c, 0x0e, 0xd9,
	0x6a, 0xc6, 0x3d, 0xee, 0x13, 0xbd, 0x24, 0xf1, 0x8d, 0x8d, 0x4f, 0x41, 0x63, 0xdf, 0xd3, 0x88,
	0xf7, 0x08, 0x73, 0x22, 0x2f, 0xe4, 0x1e, 0x0d, 0xf4, 0x03, 0xc9, 0xc9, 0xe1, 0xf8, 0x25, 0x00,
	0x9d, 0xcf, 0x49, 0xc4, 0x5e, 0x11, 0x6e, 0xeb, 0xe5, 0x86, 0xd2, 0xac, 0xb5, 0x3f, 0x68, 0x15,
	0x54, 0xd8, 0x1a, 0x6e, 0x68, 0x66, 0xca, 0x05, 0x1f, 0x43, 0x25, 0xb2, 0xb9, 0x17, 0x2c, 0xf4,
	0x4a, 0x43, 0x69, 0xd6, 0xcd, 0xc4, 0x42, 0x0d, 0x4a, 0xc4, 0x0e, 0xf4, 0xaa, 0xcc, 0x2b, 0x96,
	0x02, 0x59, 0x84, 0x8e, 0x7e, 0x18, 0x23, 0x8b, 0xd0, 0x11, 0x85, 0x3a, 0x11, 0xb1, 0x39, 0x71,
	0xc7, 0xde, 0x92, 0x30, 0x6e, 0x2f, 0x43, 0xfd, 0xa8, 0xa1, 0x34, 0x0f, 0xcc, 0x1c, 0x2e, 0xb8,
	0xab, 0xd0, 0xdd, 0xe5, 0x42, 0xcc, 0xcd, 0xe2, 0x46, 0x04, 0x30, 0xdc, 0xa9, 0x70, 0x46, 0x7d,
	0x87, 0x2e, 0xa5, 0xa4, 0x75, 0x33, 0xb1, 0xb0, 0x09, 0x0f, 0x02, 0x1a, 0x8c, 0x22, 0x3a, 0x27,
	0x8c, 0x79, 0x34, 0xb0, 0x7d, 0xa9, 0x70, 0xdd, 0xcc, 0xc2, 0x68, 0xc0, 0x71, 0x98, 0xa6, 0x95,
	0x24, 0x6d, 0x07, 0x33, 0xfe, 0x52, 0xa0, 0x2c, 0x93, 0xe6, 0xda, 0xa7, 0x43, 0x55, 0xea, 0x75,
	0xe9, 0x26, 0x1d, 0x5c, 0x9b, 0xf8, 0x04, 0x8e, 0xc2, 0xb8, 0xe7, 0x97, 0x6e, 0xd2, 0xc5, 0x2d,
	0x80, 0xa7, 0x50, 0x0e, 0x23, 0xcf, 0x21, 0x49, 0xef, 0x62, 0x43, 0xf8, 0xf8, 0x1e, 0xe3, 0x23,
	0xf9, 0xa5, 0x1c, 0xfb, 0x6c, 0x00, 0x7c, 0x0e, 0x15, 0x46, 0x7c, 0x9f, 0x44, 0xb2, 0x1b, 0xb5,
	0xf6, 0x7b, 0x85, 0xad, 0xb4, 0x24, 0xc5, 0x4c, 0xa8, 0x22, 0xe4, 0x8c, 0x30, 0x2e, 0xab, 0x97,
	0x0d, 0x3b, 0x34, 0xb7, 0x80, 0xf1, 0x0d, 0x54, 0x62, 0x7e, 0x6e, 0x63, 0x62, 0x06, 0xe5, 0x97,
	0xcd, 0xce, 0x36, 0x36, 0x36, 0xa0, 0xe6, 0x7a, 0x2c, 0xf4, 0xed, 0x9f, 0x07, 0x62, 0x74, 0xe3,
	0xcd, 0xa5, 0x21, 0xe3, 0x02, 0xf0, 0x4a, 0xd6, 0x2d, 0xf7, 0x6b, 0x92, 0x1f, 0x56, 0x84, 0x71,
	0x7c, 0x06, 0xe5, 0xd0, 0x5e, 0x90, 0x48, 0xa6, 0xa9, 0xb5, 0xcf, 0x0a, 0xeb, 0x1f, 0x09, 0x86,
	0x19, 0x13, 0x0d, 0x1b, 0xca, 0xd2, 0x16, 0x7a, 0xf9, 0xde, 0xd2, 0xe3, 0xd2, 0xb5, 0x6c, 0xc6,
	0x06, 0x7e, 0x08, 0xf5, 0x79, 0x44, 0x97, 0xdb, 0xa1, 0x51, 0xe5, 0xd0, 0xec, 0x82, 0x42, 0x02,
	0x9b, 0x39, 0x24, 0x70, 0xc5, 0x20, 0x97, 0x62, 0x09, 0x36, 0x80, 0xf1, 0x9b, 0x02, 0xa7, 0x13,
	0x39, 0x64, 0x99, 0x6a, 0x2f, 0xe0, 0x01, 0xf9, 0x29, 0x24, 0x0e, 0x27, 0x6e, 0xf2, 0x25, 0xa9,
	0xfb, 0x49, 0x71, 0xdd, 0x89, 0x77, 0xd6, 0x09, 0xbf, 0x00, 0x08, 0xc8, 0x8f, 0xeb, 0x10, 0xea,
	0x1e, 0x21, 0x52, 0x7c, 0xe3, 0x17, 0x15, 0x1e, 0x65, 0xca, 0x63, 0x21, 0x0d, 0x18, 0xc1, 0x17,
	0x50, 0x75, 0x56, 0x51, 0x44, 0x82, 0xfd, 0xea, 0x5a, 0x93, 0xf1, 0x12, 0x2a, 0x8c, 0xdb, 0x7c,
	0xc5, 0x64, 0x2d, 0x27, 0xed, 0xf3, 0x42, 0xb7, 0xc2, 0x9c, 0x2d, 0x4b, 0x3a, 0x9a, 0x49, 0x00,
	0xc3, 0x85, 0x4a, 0x8c, 0xe0, 0x29, 0x68, 0x93, 0x41, 0xff, 0x7a, 0xd4, 0xef, 0x8e, 0xfb, 0xbd,
	0x69, 0xdf, 0x34, 0x87, 0xa6, 0xf6, 0x0e, 0xd6, 0xa0, 0x6a, 0x4d, 0xba, 0xdd, 0xbe, 0x65, 0x69,
	0x0a, 0x3e, 0x06, 0x1c, 0x0c, 0xc7, 0xd3, 0xfe, 0xeb, 0x49, 0xe7, 0x6a, 0xba, 0xa6, 0x6a, 0x2a,
	0xd6, 0xe1, 0x48, 0xe2, 0xd7, 0x97, 0xd6, 0x58, 0x2b, 0xa1, 0x06, 0xc7, 0xd6, 0x9b, 0xc1, 0xb8,
	0x73, 0x9d, 0x44, 0x39, 0x30, 0x06, 0x70, 0xda, 0x23, 0x3e, 0xc9, 0x35, 0xe8, 0x05, 0x54, 0xc3,
	0x3b, 0x34, 0x66, 0x4d, 0x36, 0x7e, 0x57, 0xe0, 0x51, 0x26, 0x60, 0x22, 0xe9, 0x56, 0x1a, 0xe5,
	0x16, 0x69, 0x0a, 0x7d, 0xb3, 0xd2, 0x7c, 0x7e, 0x17, 0x69, 0x12, 0x09, 0x2e, 0x86, 0x93, 0x41,
	0x4f, 0x53, 0x8d, 0xaf, 0xe1, 0xe1, 0x57, 0x84, 0xdf, 0xd3, 0x6e, 0xff, 0x54, 0x00, 0xd3, 0xd1,
	0xb6, 0xd3, 0xf3, 0x5f, 0xc2, 0xe1, 0x45, 0x66, 0x7a, 0x5a, 0x85, 0x6e, 0xf9, 0x84, 0xf7, 0xac,
	0x4f, 0xc7, 0x75, 0xef, 0x49, 0x9f, 0x5f, 0x55, 0xc0, 0x74, 0xb4, 0xff, 0x45, 0x9f, 0x7c, 0xc2,
	0x8c, 0x3e, 0xe2, 0x6a, 0x8b, 0x57, 0xaf, 0x08, 0x63, 0xf6, 0x62, 0x7d, 0xcb, 0xee, 0x82, 0xc6,
	0xeb, 0xbb, 0xa8, 0x88, 0x70, 0xd2, 0xb9, 0x32, 0xfb, 0x9d, 0xde, 0x9b, 0xf8, 0xb0, 0x59, 0x9a,
	0x2a, 0x4e, 0xdb, 0xcb, 0x4e, 0x6f, 0xda, 0x1d, 0x0e, 0xc6, 0xfd, 0xc1, 0xd8, 0xd2, 0x4a, 0xed,
	0xbf, 0x4b, 0xf0, 0xf0, 0x25, 0xf5, 0xbb, 0x71, 0xc5, 0x16, 0x89, 0xde, 0x8a, 0xb7, 0xe7, 0x3b,
	0x00, 0x7b, 0x53, 0x33, 0x7e, 0xf4, 0xaf, 0x9b, 0x92, 0x3d, 0x39, 0xfb, 0x78, 0xcf, 0xcd, 0x8b,
	0xf0, 0x8b, 0xcd, 0xc8, 0xdc, 0x10, 0x3e, 0x77, 0x24, 0xf6, 0x0f, 0x3f, 0x87, 0xba, 0x9b, 0x3e,
	0xb4, 0xf8, 0xc9, 0x3e, 0x07, 0x3b, 0x4e, 0xf2, 0x74, 0xff, 0x3b, 0x40, 0xe4, 0x59, 0xa5, 0xef,
	0xcd, 0x1b, 0xf2, 0x14, 0x3d, 0x37, 0x37, 0xe4, 0x29, 0xbe, 0xfa, 0xbf, 0x85, 0xe3, 0xd4, 0xf3,
	0xca, 0xb0, 0x58, 0x88, 0xfc, 0x0b, 0x7c, 0x76, 0xeb, 0x10, 0x3f, 0x53, 0x66, 0x15, 0xf9, 0x17,
	0xfb, 0xfc, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xd6, 0x83, 0xf9, 0xe6, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BolCatalogServiceClient is the client API for BolCatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BolCatalogServiceClient interface {
	// Add a product to the catalog
	AddProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error)
	// Gets a product from the catalog, identified by its ID or EAN
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error)
	// Deletes a product from the catalog, identified by its ID or EAN
	DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error)
	// Updates a product within the catalog
	UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error)
	ListProducts(ctx context.Context, in *ListProductRequest, opts ...grpc.CallOption) (BolCatalogService_ListProductsClient, error)
}

type bolCatalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBolCatalogServiceClient(cc grpc.ClientConnInterface) BolCatalogServiceClient {
	return &bolCatalogServiceClient{cc}
}

func (c *bolCatalogServiceClient) AddProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error) {
	out := new(AddProductResponse)
	err := c.cc.Invoke(ctx, "/bol_catalog_v1beta1.BolCatalogService/addProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bolCatalogServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error) {
	out := new(AddProductResponse)
	err := c.cc.Invoke(ctx, "/bol_catalog_v1beta1.BolCatalogService/getProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bolCatalogServiceClient) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error) {
	out := new(DeleteProductResponse)
	err := c.cc.Invoke(ctx, "/bol_catalog_v1beta1.BolCatalogService/deleteProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bolCatalogServiceClient) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error) {
	out := new(UpdateProductResponse)
	err := c.cc.Invoke(ctx, "/bol_catalog_v1beta1.BolCatalogService/updateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bolCatalogServiceClient) ListProducts(ctx context.Context, in *ListProductRequest, opts ...grpc.CallOption) (BolCatalogService_ListProductsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BolCatalogService_serviceDesc.Streams[0], "/bol_catalog_v1beta1.BolCatalogService/ListProducts", opts...)
	if err != nil {
		return nil, err
	}
	x := &bolCatalogServiceListProductsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BolCatalogService_ListProductsClient interface {
	Recv() (*Product, error)
	grpc.ClientStream
}

type bolCatalogServiceListProductsClient struct {
	grpc.ClientStream
}

func (x *bolCatalogServiceListProductsClient) Recv() (*Product, error) {
	m := new(Product)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BolCatalogServiceServer is the server API for BolCatalogService service.
type BolCatalogServiceServer interface {
	// Add a product to the catalog
	AddProduct(context.Context, *AddProductRequest) (*AddProductResponse, error)
	// Gets a product from the catalog, identified by its ID or EAN
	GetProduct(context.Context, *GetProductRequest) (*AddProductResponse, error)
	// Deletes a product from the catalog, identified by its ID or EAN
	DeleteProduct(context.Context, *DeleteProductRequest) (*DeleteProductResponse, error)
	// Updates a product within the catalog
	UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductResponse, error)
	ListProducts(*ListProductRequest, BolCatalogService_ListProductsServer) error
}

// UnimplementedBolCatalogServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBolCatalogServiceServer struct {
}

func (*UnimplementedBolCatalogServiceServer) AddProduct(ctx context.Context, req *AddProductRequest) (*AddProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProduct not implemented")
}
func (*UnimplementedBolCatalogServiceServer) GetProduct(ctx context.Context, req *GetProductRequest) (*AddProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (*UnimplementedBolCatalogServiceServer) DeleteProduct(ctx context.Context, req *DeleteProductRequest) (*DeleteProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (*UnimplementedBolCatalogServiceServer) UpdateProduct(ctx context.Context, req *UpdateProductRequest) (*UpdateProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (*UnimplementedBolCatalogServiceServer) ListProducts(req *ListProductRequest, srv BolCatalogService_ListProductsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListProducts not implemented")
}

func RegisterBolCatalogServiceServer(s *grpc.Server, srv BolCatalogServiceServer) {
	s.RegisterService(&_BolCatalogService_serviceDesc, srv)
}

func _BolCatalogService_AddProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BolCatalogServiceServer).AddProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bol_catalog_v1beta1.BolCatalogService/AddProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BolCatalogServiceServer).AddProduct(ctx, req.(*AddProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BolCatalogService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BolCatalogServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bol_catalog_v1beta1.BolCatalogService/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BolCatalogServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BolCatalogService_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BolCatalogServiceServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bol_catalog_v1beta1.BolCatalogService/DeleteProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BolCatalogServiceServer).DeleteProduct(ctx, req.(*DeleteProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BolCatalogService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BolCatalogServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bol_catalog_v1beta1.BolCatalogService/UpdateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BolCatalogServiceServer).UpdateProduct(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BolCatalogService_ListProducts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListProductRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BolCatalogServiceServer).ListProducts(m, &bolCatalogServiceListProductsServer{stream})
}

type BolCatalogService_ListProductsServer interface {
	Send(*Product) error
	grpc.ServerStream
}

type bolCatalogServiceListProductsServer struct {
	grpc.ServerStream
}

func (x *bolCatalogServiceListProductsServer) Send(m *Product) error {
	return x.ServerStream.SendMsg(m)
}

var _BolCatalogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bol_catalog_v1beta1.BolCatalogService",
	HandlerType: (*BolCatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addProduct",
			Handler:    _BolCatalogService_AddProduct_Handler,
		},
		{
			MethodName: "getProduct",
			Handler:    _BolCatalogService_GetProduct_Handler,
		},
		{
			MethodName: "deleteProduct",
			Handler:    _BolCatalogService_DeleteProduct_Handler,
		},
		{
			MethodName: "updateProduct",
			Handler:    _BolCatalogService_UpdateProduct_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListProducts",
			Handler:       _BolCatalogService_ListProducts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bol-catalog/bol_catalog.proto",
}
