// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: bol-catalog/bol_catalog.proto

package bol_catalog_v1beta1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type UpdateProductResponse_Status int32

const (
	UpdateProductResponse_UNEXPECTED_ERROR UpdateProductResponse_Status = 0
	UpdateProductResponse_SUCCESS          UpdateProductResponse_Status = 1
	// The product you provided as the "expectedProduct" does not match the product in the database, this usually means
	UpdateProductResponse_NOT_EQUAL_EXPECTED UpdateProductResponse_Status = 2
	// The product by the id does not exist
	UpdateProductResponse_NOT_EXIST UpdateProductResponse_Status = 3
	// Eg. when the id fields of the newProduct and expectedProduct do not match
	UpdateProductResponse_SYNTAX_ERROR UpdateProductResponse_Status = 4
)

// Enum value maps for UpdateProductResponse_Status.
var (
	UpdateProductResponse_Status_name = map[int32]string{
		0: "UNEXPECTED_ERROR",
		1: "SUCCESS",
		2: "NOT_EQUAL_EXPECTED",
		3: "NOT_EXIST",
		4: "SYNTAX_ERROR",
	}
	UpdateProductResponse_Status_value = map[string]int32{
		"UNEXPECTED_ERROR":   0,
		"SUCCESS":            1,
		"NOT_EQUAL_EXPECTED": 2,
		"NOT_EXIST":          3,
		"SYNTAX_ERROR":       4,
	}
)

func (x UpdateProductResponse_Status) Enum() *UpdateProductResponse_Status {
	p := new(UpdateProductResponse_Status)
	*p = x
	return p
}

func (x UpdateProductResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateProductResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_bol_catalog_bol_catalog_proto_enumTypes[0].Descriptor()
}

func (UpdateProductResponse_Status) Type() protoreflect.EnumType {
	return &file_bol_catalog_bol_catalog_proto_enumTypes[0]
}

func (x UpdateProductResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateProductResponse_Status.Descriptor instead.
func (UpdateProductResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_bol_catalog_bol_catalog_proto_rawDescGZIP(), []int{7, 0}
}

type DeleteProductResponse_Status int32

const (
	DeleteProductResponse_UNEXPECTED_ERROR DeleteProductResponse_Status = 0
	// Delete was successful
	DeleteProductResponse_SUCCESS DeleteProductResponse_Status = 1
	// Product was not found, usually when the deletion already happened.
	DeleteProductResponse_NOT_FOUND DeleteProductResponse_Status = 2
)

// Enum value maps for DeleteProductResponse_Status.
var (
	DeleteProductResponse_Status_name = map[int32]string{
		0: "UNEXPECTED_ERROR",
		1: "SUCCESS",
		2: "NOT_FOUND",
	}
	DeleteProductResponse_Status_value = map[string]int32{
		"UNEXPECTED_ERROR": 0,
		"SUCCESS":          1,
		"NOT_FOUND":        2,
	}
)

func (x DeleteProductResponse_Status) Enum() *DeleteProductResponse_Status {
	p := new(DeleteProductResponse_Status)
	*p = x
	return p
}

func (x DeleteProductResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteProductResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_bol_catalog_bol_catalog_proto_enumTypes[1].Descriptor()
}

func (DeleteProductResponse_Status) Type() protoreflect.EnumType {
	return &file_bol_catalog_bol_catalog_proto_enumTypes[1]
}

func (x DeleteProductResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteProductResponse_Status.Descriptor instead.
func (DeleteProductResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_bol_catalog_bol_catalog_proto_rawDescGZIP(), []int{9, 0}
}

type GetProductResponse_Status int32

const (
	GetProductResponse_UNEXPECTED_ERROR GetProductResponse_Status = 0
	GetProductResponse_SUCCESS          GetProductResponse_Status = 1
	GetProductResponse_NOT_FOUND        GetProductResponse_Status = 2
)

// Enum value maps for GetProductResponse_Status.
var (
	GetProductResponse_Status_name = map[int32]string{
		0: "UNEXPECTED_ERROR",
		1: "SUCCESS",
		2: "NOT_FOUND",
	}
	GetProductResponse_Status_value = map[string]int32{
		"UNEXPECTED_ERROR": 0,
		"SUCCESS":          1,
		"NOT_FOUND":        2,
	}
)

func (x GetProductResponse_Status) Enum() *GetProductResponse_Status {
	p := new(GetProductResponse_Status)
	*p = x
	return p
}

func (x GetProductResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetProductResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_bol_catalog_bol_catalog_proto_enumTypes[2].Descriptor()
}

func (GetProductResponse_Status) Type() protoreflect.EnumType {
	return &file_bol_catalog_bol_catalog_proto_enumTypes[2]
}

func (x GetProductResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetProductResponse_Status.Descriptor instead.
func (GetProductResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_bol_catalog_bol_catalog_proto_rawDescGZIP(), []int{11, 0}
}

type AddProductResponse_Status int32

const (
	// Something unexpected happened
	AddProductResponse_UNEXPECTED_ERROR AddProductResponse_Status = 0
	AddProductResponse_SUCCESS          AddProductResponse_Status = 1
	// When a product with one of the identifying fields already exists
	AddProductResponse_ALREADY_EXISTS AddProductResponse_Status = 2
	// When the id is set or you forgot to add the ean field
	AddProductResponse_SYNTAX_ERROR AddProductResponse_Status = 3
)

// Enum value maps for AddProductResponse_Status.
var (
	AddProductResponse_Status_name = map[int32]string{
		0: "UNEXPECTED_ERROR",
		1: "SUCCESS",
		2: "ALREADY_EXISTS",
		3: "SYNTAX_ERROR",
	}
	AddProductResponse_Status_value = map[string]int32{
		"UNEXPECTED_ERROR": 0,
		"SUCCESS":          1,
		"ALREADY_EXISTS":   2,
		"SYNTAX_ERROR":     3,
	}
)

func (x AddProductResponse_Status) Enum() *AddProductResponse_Status {
	p := new(AddProductResponse_Status)
	*p = x
	return p
}

func (x AddProductResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddProductResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_bol_catalog_bol_catalog_proto_enumTypes[3].Descriptor()
}

func (AddProductResponse_Status) Type() protoreflect.EnumType {
	return &file_bol_catalog_bol_catalog_proto_enumTypes[3]
}

func (x AddProductResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddProductResponse_Status.Descriptor instead.
func (AddProductResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_bol_catalog_bol_catalog_proto_rawDescGZIP(), []int{13, 0}
}

// A product within the bol.com catalog.
type Product struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// a unique identifier that is unrelated to bol.com
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The product name, also called title
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The product subtitle
	Subtitle string `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	// A short description of the product
	ShortDescription string `protobuf:"bytes,4,opt,name=shortDescription,proto3" json:"shortDescription,omitempty"`
	// Contains the amount of various types of sellers
	OffersMeta *OffersMeta `protobuf:"bytes,5,opt,name=offersMeta,proto3" json:"offersMeta,omitempty"`
	// Average product rating, scale 00-50, representing 0 to 5 stars
	Rating uint32 `protobuf:"varint,6,opt,name=rating,proto3" json:"rating,omitempty"`
	// The EAN code of the product
	Ean string `protobuf:"bytes,7,opt,name=ean,proto3" json:"ean,omitempty"`
	// The GPC classification for the product
	Gpc string `protobuf:"bytes,8,opt,name=gpc,proto3" json:"gpc,omitempty"`
	// Time the product record was initially created, do not update/set this manually.
	CreatedTimestamp int64 `protobuf:"varint,9,opt,name=createdTimestamp,proto3" json:"createdTimestamp,omitempty"`
	// Last time the data for this product was updated, unix timestamp, do not update/set this manually
	UpdatedTimestamp int64 `protobuf:"varint,10,opt,name=updatedTimestamp,proto3" json:"updatedTimestamp,omitempty"`
}

func (x *Product) Reset() {
	*x = Product{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bol_catalog_bol_catalog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_bol_catalog_bol_catalog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_bol_catalog_bol_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *Product) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *Product) GetOffersMeta() *OffersMeta {
	if x != nil {
		return x.OffersMeta
	}
	return nil
}

func (x *Product) GetRating() uint32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Product) GetEan() string {
	if x != nil {
		return x.Ean
	}
	return ""
}

func (x *Product) GetGpc() string {
	if x != nil {
		return x.Gpc
	}
	return ""
}

func (x *Product) GetCreatedTimestamp() int64 {
	if x != nil {
		return x.CreatedTimestamp
	}
	return 0
}

func (x *Product) GetUpdatedTimestamp() int64 {
	if x != nil {
		return x.UpdatedTimestamp
	}
	return 0
}

// Metadata of the sellers of a product (just contains the amount of sellers of each type)
type OffersMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The number of bol.com offers for the product
	Bolcom uint32 `protobuf:"varint,1,opt,name=bolcom,proto3" json:"bolcom,omitempty"`
	// The number of nonprofessional sellers for the product
	NonProfessional uint32 `protobuf:"varint,2,opt,name=nonProfessional,proto3" json:"nonProfessional,omitempty"`
	// The number of professional seller offers for the product
	Professional uint32 `protobuf:"varint,3,opt,name=professional,proto3" json:"professional,omitempty"`
}

func (x *OffersMeta) Reset() {
	*x = OffersMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bol_catalog_bol_catalog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OffersMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OffersMeta) ProtoMessage() {}

func (x *OffersMeta) ProtoReflect() protoreflect.Message {
	mi := &file_bol_catalog_bol_catalog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OffersMeta.ProtoReflect.Descriptor instead.
func (*OffersMeta) Descriptor() ([]byte, []int) {
	return file_bol_catalog_bol_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *OffersMeta) GetBolcom() uint32 {
	if x != nil {
		return x.Bolcom
	}
	return 0
}

func (x *OffersMeta) GetNonProfessional() uint32 {
	if x != nil {
		return x.NonProfessional
	}
	return 0
}

func (x *OffersMeta) GetProfessional() uint32 {
	if x != nil {
		return x.Professional
	}
	return 0
}

type Offer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Uniquely generated id for the offer, note this is not the bol.com offerId
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The offer ID by Bol.
	OfferId string `protobuf:"bytes,2,opt,name=offerId,proto3" json:"offerId,omitempty"`
	// The unique id of the product this offer relates to (see Product)
	ProductId string `protobuf:"bytes,3,opt,name=productId,proto3" json:"productId,omitempty"`
	// The bol.com price, format 19.95
	Price string `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	// The list price, format 19.95
	ListPrice string `protobuf:"bytes,5,opt,name=listPrice,proto3" json:"listPrice,omitempty"`
	//The seller of the product
	Seller *Seller `protobuf:"bytes,6,opt,name=seller,proto3" json:"seller,omitempty"`
	// Whether this offer is the best offer
	BestOffer bool `protobuf:"varint,7,opt,name=bestOffer,proto3" json:"bestOffer,omitempty"`
}

func (x *Offer) Reset() {
	*x = Offer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bol_catalog_bol_catalog_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offer) ProtoMessage() {}

func (x *Offer) ProtoReflect() protoreflect.Message {
	mi := &file_bol_catalog_bol_catalog_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offer.ProtoReflect.Descriptor instead.
func (*Offer) Descriptor() ([]byte, []int) {
	return file_bol_catalog_bol_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *Offer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Offer) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *Offer) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Offer) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Offer) GetListPrice() string {
	if x != nil {
		return x.ListPrice
	}
	return ""
}

func (x *Offer) GetSeller() *Seller {
	if x != nil {
		return x.Seller
	}
	return nil
}

func (x *Offer) GetBestOffer() bool {
	if x != nil {
		return x.BestOffer
	}
	return false
}

type Seller struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Uniquely generated id, not the bol id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Bol.com assigned id
	SellerId string `protobuf:"bytes,2,opt,name=sellerId,proto3" json:"sellerId,omitempty"`
	// Display name for the seller
	DisplayName string `protobuf:"bytes,3,opt,name=displayName,proto3" json:"displayName,omitempty"`
}

func (x *Seller) Reset() {
	*x = Seller{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bol_catalog_bol_catalog_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Seller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seller) ProtoMessage() {}

func (x *Seller) ProtoReflect() protoreflect.Message {
	mi := &file_bol_catalog_bol_catalog_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seller.ProtoReflect.Descriptor instead.
func (*Seller) Descriptor() ([]byte, []int) {
	return file_bol_catalog_bol_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *Seller) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Seller) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *Seller) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// You should only assume there are no new products when the server returns 0 products.
// In case your ascending you can also add another check when the latest timestamp comes close to the present.
// This way you don't keep following up on newly added products.
type ListProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pager *Pager `protobuf:"bytes,1,opt,name=pager,proto3" json:"pager,omitempty"` // Handles the paging for this list
}

func (x *ListProductRequest) Reset() {
	*x = ListProductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bol_catalog_bol_catalog_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductRequest) ProtoMessage() {}

func (x *ListProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bol_catalog_bol_catalog_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductRequest.ProtoReflect.Descriptor instead.
func (*ListProductRequest) Descriptor() ([]byte, []int) {
	return file_bol_catalog_bol_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *ListProductRequest) GetPager() *Pager {
	if x != nil {
		return x.Pager
	}
	return nil
}

// A pager helps with paging through lists of resources.
// We recommend listing in descending from the current time until there are no more resources.
type Pager struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The maximum amount of items to return. The server may also enforce a maximum server-side (Default is around 100).
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Start the list from this timestamp, set ascending to list items with a createdTimestamp greater then fromTimestamp,
	// descending from less then.
	FromTimestamp int64 `protobuf:"varint,2,opt,name=fromTimestamp,proto3" json:"fromTimestamp,omitempty"`
	// if set to true it will return items created after fromTimestamp, otherwise before fromTimestamp.
	Ascending bool `protobuf:"varint,3,opt,name=ascending,proto3" json:"ascending,omitempty"`
}

func (x *Pager) Reset() {
	*x = Pager{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bol_catalog_bol_catalog_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pager) ProtoMessage() {}

func (x *Pager) ProtoReflect() protoreflect.Message {
	mi := &file_bol_catalog_bol_catalog_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pager.ProtoReflect.Descriptor instead.
func (*Pager) Descriptor() ([]byte, []int) {
	return file_bol_catalog_bol_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *Pager) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pager) GetFromTimestamp() int64 {
	if x != nil {
		return x.FromTimestamp
	}
	return 0
}

func (x *Pager) GetAscending() bool {
	if x != nil {
		return x.Ascending
	}
	return false
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The product you are expecting (not setting this will force override the product).
	// Fields that are not set will not be changed. Deleting fields is currently not supported (other then setting them to 0 or "").
	ExpectedProduct *Product `protobuf:"bytes,1,opt,name=expectedProduct,proto3" json:"expectedProduct,omitempty"`
	// The new version of the product (ean and id should be the same as the expected_product or SYNTAX_ERROR will be returned)
	NewProduct *Product `protobuf:"bytes,2,opt,name=newProduct,proto3" json:"newProduct,omitempty"`
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bol_catalog_bol_catalog_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bol_catalog_bol_catalog_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_bol_catalog_bol_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProductRequest) GetExpectedProduct() *Product {
	if x != nil {
		return x.ExpectedProduct
	}
	return nil
}

func (x *UpdateProductRequest) GetNewProduct() *Product {
	if x != nil {
		return x.NewProduct
	}
	return nil
}

type UpdateProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The current product after the update (or when the update was not successful)
	Current *Product                     `protobuf:"bytes,1,opt,name=current,proto3" json:"current,omitempty"`
	Status  UpdateProductResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=bol_catalog_v1beta1.UpdateProductResponse_Status" json:"status,omitempty"`
}

func (x *UpdateProductResponse) Reset() {
	*x = UpdateProductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bol_catalog_bol_catalog_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResponse) ProtoMessage() {}

func (x *UpdateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bol_catalog_bol_catalog_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return file_bol_catalog_bol_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProductResponse) GetCurrent() *Product {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *UpdateProductResponse) GetStatus() UpdateProductResponse_Status {
	if x != nil {
		return x.Status
	}
	return UpdateProductResponse_UNEXPECTED_ERROR
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The product to delete: One of the identifying fields (ean, id) should be set.
	Product *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bol_catalog_bol_catalog_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bol_catalog_bol_catalog_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_bol_catalog_bol_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteProductRequest) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type DeleteProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Whether or not the deletion was successful
	Status DeleteProductResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=bol_catalog_v1beta1.DeleteProductResponse_Status" json:"status,omitempty"`
}

func (x *DeleteProductResponse) Reset() {
	*x = DeleteProductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bol_catalog_bol_catalog_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResponse) ProtoMessage() {}

func (x *DeleteProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bol_catalog_bol_catalog_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return file_bol_catalog_bol_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteProductResponse) GetStatus() DeleteProductResponse_Status {
	if x != nil {
		return x.Status
	}
	return DeleteProductResponse_UNEXPECTED_ERROR
}

type GetProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// One of the identifying fields should be set (ean, id), all other fields can be left empty (but will also cause filtering when set).
	Product *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bol_catalog_bol_catalog_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bol_catalog_bol_catalog_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_bol_catalog_bol_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *GetProductRequest) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type GetProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The actual stored product
	Product *Product                  `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Status  GetProductResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=bol_catalog_v1beta1.GetProductResponse_Status" json:"status,omitempty"`
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bol_catalog_bol_catalog_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bol_catalog_bol_catalog_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_bol_catalog_bol_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *GetProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *GetProductResponse) GetStatus() GetProductResponse_Status {
	if x != nil {
		return x.Status
	}
	return GetProductResponse_UNEXPECTED_ERROR
}

type AddProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The product to add, id may not be set (but ean should)
	Product *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
}

func (x *AddProductRequest) Reset() {
	*x = AddProductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bol_catalog_bol_catalog_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductRequest) ProtoMessage() {}

func (x *AddProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bol_catalog_bol_catalog_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductRequest.ProtoReflect.Descriptor instead.
func (*AddProductRequest) Descriptor() ([]byte, []int) {
	return file_bol_catalog_bol_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *AddProductRequest) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type AddProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The actual product in the database (with the unique id). This is set on SUCCESS and ALREADY_EXISTS.
	Product *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	// The status code of the request
	Status AddProductResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=bol_catalog_v1beta1.AddProductResponse_Status" json:"status,omitempty"`
	// Some extra information regarding the status code, optional.
	StatusMessage string `protobuf:"bytes,3,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
}

func (x *AddProductResponse) Reset() {
	*x = AddProductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bol_catalog_bol_catalog_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductResponse) ProtoMessage() {}

func (x *AddProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bol_catalog_bol_catalog_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductResponse.ProtoReflect.Descriptor instead.
func (*AddProductResponse) Descriptor() ([]byte, []int) {
	return file_bol_catalog_bol_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *AddProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *AddProductResponse) GetStatus() AddProductResponse_Status {
	if x != nil {
		return x.Status
	}
	return AddProductResponse_UNEXPECTED_ERROR
}

func (x *AddProductResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

var File_bol_catalog_bol_catalog_proto protoreflect.FileDescriptor

var file_bol_catalog_bol_catalog_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x62, 0x6f, 0x6c, 0x2d, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2f, 0x62, 0x6f,
	0x6c, 0x5f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x13, 0x62, 0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x76, 0x31, 0x62,
	0x65, 0x74, 0x61, 0x31, 0x22, 0xca, 0x02, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x2a, 0x0a, 0x10, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3f, 0x0a, 0x0a,
	0x6f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x62, 0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x76,
	0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x4d, 0x65, 0x74,
	0x61, 0x52, 0x0a, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x61, 0x6e, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x65, 0x61, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x70, 0x63, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x67, 0x70, 0x63, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x10, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2a, 0x0a, 0x10, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x10, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x22, 0x72, 0x0a, 0x0a, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x4d, 0x65, 0x74, 0x61, 0x12,
	0x16, 0x0a, 0x06, 0x62, 0x6f, 0x6c, 0x63, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x62, 0x6f, 0x6c, 0x63, 0x6f, 0x6d, 0x12, 0x28, 0x0a, 0x0f, 0x6e, 0x6f, 0x6e, 0x50, 0x72,
	0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0f, 0x6e, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x22, 0xd6, 0x01, 0x0a, 0x05, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x6c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73,
	0x65, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x62, 0x6f,
	0x6c, 0x5f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61,
	0x31, 0x2e, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x06, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72,
	0x12, 0x1c, 0x0a, 0x09, 0x62, 0x65, 0x73, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x62, 0x65, 0x73, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x22, 0x56,
	0x0a, 0x06, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x6c,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x6c,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x46, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x05,
	0x70, 0x61, 0x67, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x6f,
	0x6c, 0x5f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61,
	0x31, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x72, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x72, 0x22, 0x61,
	0x0a, 0x05, 0x50, 0x61, 0x67, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x24, 0x0a,
	0x0d, 0x66, 0x72, 0x6f, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x66, 0x72, 0x6f, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x73, 0x63, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x73, 0x63, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x22, 0x9c, 0x01, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x46, 0x0a, 0x0f, 0x65, 0x78,
	0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f,
	0x67, 0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x52, 0x0f, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x12, 0x3c, 0x0a, 0x0a, 0x6e, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x74,
	0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x22, 0x80, 0x02, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x6f,
	0x6c, 0x5f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61,
	0x31, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x12, 0x49, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x31, 0x2e, 0x62, 0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67,
	0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x64, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x4e, 0x45, 0x58, 0x50,
	0x45, 0x43, 0x54, 0x45, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x4e, 0x4f,
	0x54, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x5f, 0x45, 0x58, 0x50, 0x45, 0x43, 0x54, 0x45, 0x44,
	0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10,
	0x03, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x59, 0x4e, 0x54, 0x41, 0x58, 0x5f, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x04, 0x22, 0x4e, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x07, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62,
	0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x76, 0x31, 0x62, 0x65, 0x74,
	0x61, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x22, 0x9e, 0x01, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x31, 0x2e,
	0x62, 0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x76, 0x31, 0x62, 0x65,
	0x74, 0x61, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3a, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x4e, 0x45, 0x58, 0x50, 0x45, 0x43, 0x54, 0x45, 0x44,
	0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43,
	0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55,
	0x4e, 0x44, 0x10, 0x02, 0x22, 0x4b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x07, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x6f, 0x6c,
	0x5f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31,
	0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x22, 0xd0, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x6f, 0x6c, 0x5f,
	0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x12, 0x46, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x2e, 0x2e, 0x62, 0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x76,
	0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3a, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x4e, 0x45, 0x58, 0x50, 0x45, 0x43, 0x54, 0x45, 0x44,
	0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43,
	0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55,
	0x4e, 0x44, 0x10, 0x02, 0x22, 0x4b, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x07, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x6f, 0x6c,
	0x5f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31,
	0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x22, 0x8d, 0x02, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x6f, 0x6c, 0x5f,
	0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x12, 0x46, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x2e, 0x2e, 0x62, 0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x76,
	0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x51,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x4e, 0x45, 0x58,
	0x50, 0x45, 0x43, 0x54, 0x45, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x41,
	0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x53, 0x10, 0x02, 0x12,
	0x10, 0x0a, 0x0c, 0x53, 0x59, 0x4e, 0x54, 0x41, 0x58, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10,
	0x03, 0x32, 0xfa, 0x03, 0x0a, 0x11, 0x42, 0x6f, 0x6c, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x26, 0x2e, 0x62, 0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x74, 0x61,
	0x6c, 0x6f, 0x67, 0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e,
	0x62, 0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x76, 0x31, 0x62, 0x65,
	0x74, 0x61, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x0a, 0x67, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x12, 0x26, 0x2e, 0x62, 0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x74, 0x61, 0x6c,
	0x6f, 0x67, 0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x62,
	0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x76, 0x31, 0x62, 0x65, 0x74,
	0x61, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66, 0x0a, 0x0d, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x29, 0x2e, 0x62, 0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x74,
	0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2a, 0x2e, 0x62, 0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f,
	0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66, 0x0a,
	0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x29,
	0x2e, 0x62, 0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x76, 0x31, 0x62,
	0x65, 0x74, 0x61, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x62, 0x6f, 0x6c, 0x5f,
	0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x73, 0x12, 0x27, 0x2e, 0x62, 0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x74, 0x61,
	0x6c, 0x6f, 0x67, 0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x62, 0x6f, 0x6c, 0x5f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x76, 0x31, 0x62,
	0x65, 0x74, 0x61, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x30, 0x01, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bol_catalog_bol_catalog_proto_rawDescOnce sync.Once
	file_bol_catalog_bol_catalog_proto_rawDescData = file_bol_catalog_bol_catalog_proto_rawDesc
)

func file_bol_catalog_bol_catalog_proto_rawDescGZIP() []byte {
	file_bol_catalog_bol_catalog_proto_rawDescOnce.Do(func() {
		file_bol_catalog_bol_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(file_bol_catalog_bol_catalog_proto_rawDescData)
	})
	return file_bol_catalog_bol_catalog_proto_rawDescData
}

var file_bol_catalog_bol_catalog_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_bol_catalog_bol_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_bol_catalog_bol_catalog_proto_goTypes = []interface{}{
	(UpdateProductResponse_Status)(0), // 0: bol_catalog_v1beta1.UpdateProductResponse.Status
	(DeleteProductResponse_Status)(0), // 1: bol_catalog_v1beta1.DeleteProductResponse.Status
	(GetProductResponse_Status)(0),    // 2: bol_catalog_v1beta1.GetProductResponse.Status
	(AddProductResponse_Status)(0),    // 3: bol_catalog_v1beta1.AddProductResponse.Status
	(*Product)(nil),                   // 4: bol_catalog_v1beta1.Product
	(*OffersMeta)(nil),                // 5: bol_catalog_v1beta1.OffersMeta
	(*Offer)(nil),                     // 6: bol_catalog_v1beta1.Offer
	(*Seller)(nil),                    // 7: bol_catalog_v1beta1.Seller
	(*ListProductRequest)(nil),        // 8: bol_catalog_v1beta1.ListProductRequest
	(*Pager)(nil),                     // 9: bol_catalog_v1beta1.Pager
	(*UpdateProductRequest)(nil),      // 10: bol_catalog_v1beta1.UpdateProductRequest
	(*UpdateProductResponse)(nil),     // 11: bol_catalog_v1beta1.UpdateProductResponse
	(*DeleteProductRequest)(nil),      // 12: bol_catalog_v1beta1.DeleteProductRequest
	(*DeleteProductResponse)(nil),     // 13: bol_catalog_v1beta1.DeleteProductResponse
	(*GetProductRequest)(nil),         // 14: bol_catalog_v1beta1.GetProductRequest
	(*GetProductResponse)(nil),        // 15: bol_catalog_v1beta1.GetProductResponse
	(*AddProductRequest)(nil),         // 16: bol_catalog_v1beta1.AddProductRequest
	(*AddProductResponse)(nil),        // 17: bol_catalog_v1beta1.AddProductResponse
}
var file_bol_catalog_bol_catalog_proto_depIdxs = []int32{
	5,  // 0: bol_catalog_v1beta1.Product.offersMeta:type_name -> bol_catalog_v1beta1.OffersMeta
	7,  // 1: bol_catalog_v1beta1.Offer.seller:type_name -> bol_catalog_v1beta1.Seller
	9,  // 2: bol_catalog_v1beta1.ListProductRequest.pager:type_name -> bol_catalog_v1beta1.Pager
	4,  // 3: bol_catalog_v1beta1.UpdateProductRequest.expectedProduct:type_name -> bol_catalog_v1beta1.Product
	4,  // 4: bol_catalog_v1beta1.UpdateProductRequest.newProduct:type_name -> bol_catalog_v1beta1.Product
	4,  // 5: bol_catalog_v1beta1.UpdateProductResponse.current:type_name -> bol_catalog_v1beta1.Product
	0,  // 6: bol_catalog_v1beta1.UpdateProductResponse.status:type_name -> bol_catalog_v1beta1.UpdateProductResponse.Status
	4,  // 7: bol_catalog_v1beta1.DeleteProductRequest.product:type_name -> bol_catalog_v1beta1.Product
	1,  // 8: bol_catalog_v1beta1.DeleteProductResponse.status:type_name -> bol_catalog_v1beta1.DeleteProductResponse.Status
	4,  // 9: bol_catalog_v1beta1.GetProductRequest.product:type_name -> bol_catalog_v1beta1.Product
	4,  // 10: bol_catalog_v1beta1.GetProductResponse.product:type_name -> bol_catalog_v1beta1.Product
	2,  // 11: bol_catalog_v1beta1.GetProductResponse.status:type_name -> bol_catalog_v1beta1.GetProductResponse.Status
	4,  // 12: bol_catalog_v1beta1.AddProductRequest.product:type_name -> bol_catalog_v1beta1.Product
	4,  // 13: bol_catalog_v1beta1.AddProductResponse.product:type_name -> bol_catalog_v1beta1.Product
	3,  // 14: bol_catalog_v1beta1.AddProductResponse.status:type_name -> bol_catalog_v1beta1.AddProductResponse.Status
	16, // 15: bol_catalog_v1beta1.BolCatalogService.addProduct:input_type -> bol_catalog_v1beta1.AddProductRequest
	14, // 16: bol_catalog_v1beta1.BolCatalogService.getProduct:input_type -> bol_catalog_v1beta1.GetProductRequest
	12, // 17: bol_catalog_v1beta1.BolCatalogService.deleteProduct:input_type -> bol_catalog_v1beta1.DeleteProductRequest
	10, // 18: bol_catalog_v1beta1.BolCatalogService.updateProduct:input_type -> bol_catalog_v1beta1.UpdateProductRequest
	8,  // 19: bol_catalog_v1beta1.BolCatalogService.ListProducts:input_type -> bol_catalog_v1beta1.ListProductRequest
	17, // 20: bol_catalog_v1beta1.BolCatalogService.addProduct:output_type -> bol_catalog_v1beta1.AddProductResponse
	17, // 21: bol_catalog_v1beta1.BolCatalogService.getProduct:output_type -> bol_catalog_v1beta1.AddProductResponse
	13, // 22: bol_catalog_v1beta1.BolCatalogService.deleteProduct:output_type -> bol_catalog_v1beta1.DeleteProductResponse
	11, // 23: bol_catalog_v1beta1.BolCatalogService.updateProduct:output_type -> bol_catalog_v1beta1.UpdateProductResponse
	4,  // 24: bol_catalog_v1beta1.BolCatalogService.ListProducts:output_type -> bol_catalog_v1beta1.Product
	20, // [20:25] is the sub-list for method output_type
	15, // [15:20] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_bol_catalog_bol_catalog_proto_init() }
func file_bol_catalog_bol_catalog_proto_init() {
	if File_bol_catalog_bol_catalog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bol_catalog_bol_catalog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Product); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bol_catalog_bol_catalog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OffersMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bol_catalog_bol_catalog_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Offer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bol_catalog_bol_catalog_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Seller); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bol_catalog_bol_catalog_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListProductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bol_catalog_bol_catalog_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pager); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bol_catalog_bol_catalog_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bol_catalog_bol_catalog_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bol_catalog_bol_catalog_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteProductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bol_catalog_bol_catalog_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteProductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bol_catalog_bol_catalog_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bol_catalog_bol_catalog_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bol_catalog_bol_catalog_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddProductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bol_catalog_bol_catalog_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddProductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bol_catalog_bol_catalog_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bol_catalog_bol_catalog_proto_goTypes,
		DependencyIndexes: file_bol_catalog_bol_catalog_proto_depIdxs,
		EnumInfos:         file_bol_catalog_bol_catalog_proto_enumTypes,
		MessageInfos:      file_bol_catalog_bol_catalog_proto_msgTypes,
	}.Build()
	File_bol_catalog_bol_catalog_proto = out.File
	file_bol_catalog_bol_catalog_proto_rawDesc = nil
	file_bol_catalog_bol_catalog_proto_goTypes = nil
	file_bol_catalog_bol_catalog_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BolCatalogServiceClient is the client API for BolCatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BolCatalogServiceClient interface {
	// Add a product to the catalog
	AddProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error)
	// Gets a product from the catalog, identified by its ID or EAN
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error)
	// Deletes a product from the catalog, identified by its ID or EAN
	DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error)
	// Updates a product within the catalog
	UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error)
	ListProducts(ctx context.Context, in *ListProductRequest, opts ...grpc.CallOption) (BolCatalogService_ListProductsClient, error)
}

type bolCatalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBolCatalogServiceClient(cc grpc.ClientConnInterface) BolCatalogServiceClient {
	return &bolCatalogServiceClient{cc}
}

func (c *bolCatalogServiceClient) AddProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error) {
	out := new(AddProductResponse)
	err := c.cc.Invoke(ctx, "/bol_catalog_v1beta1.BolCatalogService/addProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bolCatalogServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error) {
	out := new(AddProductResponse)
	err := c.cc.Invoke(ctx, "/bol_catalog_v1beta1.BolCatalogService/getProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bolCatalogServiceClient) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error) {
	out := new(DeleteProductResponse)
	err := c.cc.Invoke(ctx, "/bol_catalog_v1beta1.BolCatalogService/deleteProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bolCatalogServiceClient) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error) {
	out := new(UpdateProductResponse)
	err := c.cc.Invoke(ctx, "/bol_catalog_v1beta1.BolCatalogService/updateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bolCatalogServiceClient) ListProducts(ctx context.Context, in *ListProductRequest, opts ...grpc.CallOption) (BolCatalogService_ListProductsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BolCatalogService_serviceDesc.Streams[0], "/bol_catalog_v1beta1.BolCatalogService/ListProducts", opts...)
	if err != nil {
		return nil, err
	}
	x := &bolCatalogServiceListProductsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BolCatalogService_ListProductsClient interface {
	Recv() (*Product, error)
	grpc.ClientStream
}

type bolCatalogServiceListProductsClient struct {
	grpc.ClientStream
}

func (x *bolCatalogServiceListProductsClient) Recv() (*Product, error) {
	m := new(Product)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BolCatalogServiceServer is the server API for BolCatalogService service.
type BolCatalogServiceServer interface {
	// Add a product to the catalog
	AddProduct(context.Context, *AddProductRequest) (*AddProductResponse, error)
	// Gets a product from the catalog, identified by its ID or EAN
	GetProduct(context.Context, *GetProductRequest) (*AddProductResponse, error)
	// Deletes a product from the catalog, identified by its ID or EAN
	DeleteProduct(context.Context, *DeleteProductRequest) (*DeleteProductResponse, error)
	// Updates a product within the catalog
	UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductResponse, error)
	ListProducts(*ListProductRequest, BolCatalogService_ListProductsServer) error
}

// UnimplementedBolCatalogServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBolCatalogServiceServer struct {
}

func (*UnimplementedBolCatalogServiceServer) AddProduct(context.Context, *AddProductRequest) (*AddProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProduct not implemented")
}
func (*UnimplementedBolCatalogServiceServer) GetProduct(context.Context, *GetProductRequest) (*AddProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (*UnimplementedBolCatalogServiceServer) DeleteProduct(context.Context, *DeleteProductRequest) (*DeleteProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (*UnimplementedBolCatalogServiceServer) UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (*UnimplementedBolCatalogServiceServer) ListProducts(*ListProductRequest, BolCatalogService_ListProductsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListProducts not implemented")
}

func RegisterBolCatalogServiceServer(s *grpc.Server, srv BolCatalogServiceServer) {
	s.RegisterService(&_BolCatalogService_serviceDesc, srv)
}

func _BolCatalogService_AddProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BolCatalogServiceServer).AddProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bol_catalog_v1beta1.BolCatalogService/AddProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BolCatalogServiceServer).AddProduct(ctx, req.(*AddProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BolCatalogService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BolCatalogServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bol_catalog_v1beta1.BolCatalogService/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BolCatalogServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BolCatalogService_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BolCatalogServiceServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bol_catalog_v1beta1.BolCatalogService/DeleteProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BolCatalogServiceServer).DeleteProduct(ctx, req.(*DeleteProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BolCatalogService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BolCatalogServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bol_catalog_v1beta1.BolCatalogService/UpdateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BolCatalogServiceServer).UpdateProduct(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BolCatalogService_ListProducts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListProductRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BolCatalogServiceServer).ListProducts(m, &bolCatalogServiceListProductsServer{stream})
}

type BolCatalogService_ListProductsServer interface {
	Send(*Product) error
	grpc.ServerStream
}

type bolCatalogServiceListProductsServer struct {
	grpc.ServerStream
}

func (x *bolCatalogServiceListProductsServer) Send(m *Product) error {
	return x.ServerStream.SendMsg(m)
}

var _BolCatalogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bol_catalog_v1beta1.BolCatalogService",
	HandlerType: (*BolCatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addProduct",
			Handler:    _BolCatalogService_AddProduct_Handler,
		},
		{
			MethodName: "getProduct",
			Handler:    _BolCatalogService_GetProduct_Handler,
		},
		{
			MethodName: "deleteProduct",
			Handler:    _BolCatalogService_DeleteProduct_Handler,
		},
		{
			MethodName: "updateProduct",
			Handler:    _BolCatalogService_UpdateProduct_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListProducts",
			Handler:       _BolCatalogService_ListProducts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bol-catalog/bol_catalog.proto",
}
